{"uuid": "f2f28513-7c73-405e-8b6d-82c4558ccdcb", "children": ["37b535e4-971d-4946-a49b-8cfce5a446d3", "d304701c-502e-4462-abf4-2d83fd638890"], "befores": [{"name": "login_setup", "status": "broken", "statusDetails": {"message": "KeyError: 'user'\n", "trace": "  File \"d:\\programme_software\\python36\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\programme_software\\python36\\lib\\site-packages\\_pytest\\fixtures.py\", line 1124, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\programme_software\\python36\\lib\\site-packages\\_pytest\\fixtures.py\", line 930, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\13260\\PycharmProjects\\interface_test\\testcases\\conftest.py\", line 10, in login_setup\n    login(userinfo['user'], userinfo['password'] )\n"}, "start": 1618369917387, "stop": 1618369917387}], "start": 1618369917387, "stop": 1618369919603}