{"uuid": "46de8ed1-6418-4a58-87f7-b75e741b1b5a", "children": ["d2efc3e7-a602-4344-b0ad-82515b770f02", "b93d9e34-69e2-46a9-a222-35d080c3bc15", "1eff2556-9d24-40e0-a89a-708e0bdbed5a"], "befores": [{"name": "login_setup", "status": "broken", "statusDetails": {"message": "KeyError: 'user'\n", "trace": "  File \"d:\\programme_software\\python36\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\programme_software\\python36\\lib\\site-packages\\_pytest\\fixtures.py\", line 1124, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\programme_software\\python36\\lib\\site-packages\\_pytest\\fixtures.py\", line 930, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\13260\\PycharmProjects\\interface_test\\testcases\\conftest.py\", line 11, in login_setup\n    login(userinfo['user'], userinfo['password'] )\n"}, "start": 1618369986830, "stop": 1618369986832}], "start": 1618369986830, "stop": 1618369988660}